const roles = [
  "SDE-1",
  "SDE-2",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Software Engineer",
  "Mobile App Developer",
  "Android Developer",
  "iOS Developer",
  "React Developer",
  "Node.js Developer",
  "DevOps Engineer",
  "Cloud Engineer",
  "Data Analyst",
  "Data Scientist",
  "Machine Learning Engineer",
  "AI Engineer",
  "Business Analyst",
  "Product Manager",
  "UI/UX Designer",
  "QA Engineer",
  "Test Engineer",
  "Cybersecurity Analyst",
  "Blockchain Developer",
  "Game Developer",
  "Embedded Systems Engineer",
  "Site Reliability Engineer",
  "Database Administrator",
  "System Engineer",
  "Network Engineer",
  "Technical Support Engineer",
  "Research Intern",
  "Graduate Engineer Trainee",
  "Consultant",
];
export default roles.sort();