const companies = [
  "Google",
  "Amazon",
  "Microsoft",
  "Adobe",
  "Atlassian",
  "Goldman Sachs",
  "Walmart",
  "Visa",
  "Flipkart",
  "PhonePe",
  "Fractal",
  "Tredence",
  "Cisco",
  "Swiggy",
  "Uber",
  "IBM",
  "PayPal",
  "JP Morgan",
  "Intel",
  "Oracle",
  "Accenture",
  "Futures First",
  "Mu Sigma",
  "Optum",
  "Airtel",
  "Warner Bros",
  "ACT Fibernet",
  "O9 Solutions",
  "HP",
  "CDAC",
  "Infosys",
  "TCS",
  "Wipro",
  "Cognizant",
  "Capgemini",
  "Deloitte",
  "EY",
  "PwC",
  "KPMG",
  "L&T",
  "L&T Technology Services",
  "Tech Mahindra",
  "HCLTech",
  "ZS Associates",
  "Tiger Analytics",
  "Navi",
  "Samsung",
  "Qualcomm",
  "NVIDIA",
  "AMD",
  "Media.net",
  "SAP",
  "Siemens",
  "Bosch",
  "Bajaj Finserv",
  "Razorpay",
  "Groww",
  "CRED",
  "Meesho",
  "Myntra",
  "D. E. Shaw",
  "Morgan Stanley",
  "American Express",
  "Mastercard",
  "HSBC",
  "Barclays",
  "Citi",
  "Bank of America",
  "Sprinklr",
  "ServiceNow",
  "ThoughtWorks",
  "Persistent",
  "Hexaware",
  "Publicis Sapient",
  "Arcesium",
  "Nagarro",
  "Zomato",
  "Reliance Jio",
  "Juspay",
  "Comviva",
  "C-DOT",
  "BEL",
  "DRDO",
  "ISRO",
  "NIELIT",
  "Byju's",
  "Unacademy",
  "Vedantu",
  "UpGrad",
  "Physics Wallah",
];

const roles = [
  "SDE-1",
  "SDE-2",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Software Engineer",
  "Mobile App Developer",
  "Android Developer",
  "iOS Developer",
  "React Developer",
  "Node.js Developer",
  "DevOps Engineer",
  "Cloud Engineer",
  "Data Analyst",
  "Data Scientist",
  "Machine Learning Engineer",
  "AI Engineer",
  "Business Analyst",
  "Product Manager",
  "UI/UX Designer",
  "QA Engineer",
  "Test Engineer",
  "Cybersecurity Analyst",
  "Blockchain Developer",
  "Game Developer",
  "Embedded Systems Engineer",
  "Site Reliability Engineer",
  "Database Administrator",
  "System Engineer",
  "Network Engineer",
  "Technical Support Engineer",
  "Research Intern",
  "Graduate Engineer Trainee",
  "Consultant",
];

const tags = [
  "DSA",
  "OS",
  "DBMS",
  "OOPs",
  "CN",
  "System Design",
  "LLD",
  "HLD",
  "React",
  "Next.js",
  "Node.js",
  "Express.js",
  "MongoDB",
  "Machine Learning",
  "Deep Learning",
  "Competitive Programming",
  "Cybersecurity",
  "Blockchain",
];

module.exports = {
  companies: companies.sort(),
  roles: roles.sort(),
  tags: tags.sort(),
};